import { CardData, Letter } from '../types/game';

export const CARD_DATABASE: Record<Letter, CardData> = {
  A: {
    letter: 'A',
    name: 'Amateras',
    japaneseName: '太陽神',
    points: 10,
    category: 'deity',
    description: 'ゲーム終了時に自分の手札にあった場合、10ポイント加える。',
    shortEffect: '手札保持でゲーム終了時 +10pt',
    lore: '天照大御神。太陽を司る至高の神。手に抱き続けることで絶大な光と加護をもたらす。',
    flavorQuote: '我が御光の前に闇は平伏す。',
    imageUrl: '/cards/A.jpg',
  },
  B: {
    letter: 'B',
    name: 'Brave',
    japaneseName: '勇者',
    points: 9,
    category: 'hero',
    description: 'Devil～魔王～にバトルで勝った場合、ゲームを終了しポイントに関係なく勝利する。',
    shortEffect: '魔王(D)に勝てば即座に完全勝利！',
    lore: '光の聖剣を携えし伝説の勇者。宿敵・魔王を討ち果たす宿命を背負う。',
    flavorQuote: '宿敵よ、今こそ因縁に終止符を打つ！',
    imageUrl: '/cards/B.jpg',
  },
  C: {
    letter: 'C',
    name: 'Crystal dragon',
    japaneseName: 'クリスタルドラゴン',
    points: 9,
    category: 'dragon',
    description: 'ゲーム終了時に自分の手札にあった場合、5ポイント加える。',
    shortEffect: '手札保持でゲーム終了時 +5pt',
    lore: '純粋な魔力結晶から生まれた幻の古龍。秘匿されるほど財宝としての価値が高まる。',
    flavorQuote: '透き通る鱗は太古の記憶を宿す。',
    imageUrl: '/cards/C.jpg',
  },
  D: {
    letter: 'D',
    name: 'Devil',
    japaneseName: '魔王',
    points: 8,
    category: 'demon',
    description: 'バトル終了後、ゲームを終了する。（相手の効果は発動する。）',
    shortEffect: '戦闘後、ゲームを強制終了させる',
    lore: '暗黒街を支配する冥府の覇王。その出現は世界の終焉の号砲となる。',
    flavorQuote: '我が一撃で、この世界を幕引きとしてやろう。',
    imageUrl: '/cards/D.jpg',
  },
  E: {
    letter: 'E',
    name: 'Emperor',
    japaneseName: '皇帝',
    points: 8,
    category: 'human',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '帝国の最高権力者。敗北を糧に次の兵力を即座に補給する。',
    flavorQuote: '一戦の敗北など、帝国の再建を遅らせるに過ぎぬ。',
    imageUrl: '/cards/E.jpg',
  },
  F: {
    letter: 'F',
    name: 'Fire phoenix',
    japaneseName: '火の鳥',
    points: 8,
    category: 'myth',
    description: 'バトルに負けた場合、相手のポイントにせず手札に戻す。この効果はゲーム中1度のみ発動する。',
    shortEffect: '敗北時：相手の得点にせず手札に生還 (1度のみ)',
    lore: '灰の中から何度でも甦る不死の焔鳥。自らが捕虜となることを許さない。',
    flavorQuote: '燃え盛る業火より、私は再び羽ばたく。',
    imageUrl: '/cards/F.jpg',
  },
  G: {
    letter: 'G',
    name: 'Gargoyle',
    japaneseName: 'ガーゴイル',
    points: 7,
    category: 'spirit',
    description: 'バトルに勝った場合、このバトルでの自分に対するカードの効果を受けない。',
    shortEffect: '勝利時：自身を対象とする相手効果を完全無効化',
    lore: '聖堂の屋根を守護する石造の魔獣。相手の小細工や強奪を石の皮膚で弾き返す。',
    flavorQuote: '石の意志は如何なる呪詛も寄せ付けぬ。',
    imageUrl: '/cards/G.jpg',
  },
  H: {
    letter: 'H',
    name: 'Hydra',
    japaneseName: 'ヒドラ',
    points: 7,
    category: 'dragon',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '首を斬られても二本の首が生える多頭の大蛇。倒されるたびに新たな力を生む。',
    flavorQuote: '我が首を断てると思うか？',
    imageUrl: '/cards/H.jpg',
  },
  I: {
    letter: 'I',
    name: 'Iron golem',
    japaneseName: 'アイアンゴーレム',
    points: 7,
    category: 'spirit',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '古代の鍛冶魔術で鋳造された鋼鉄の巨兵。砕かれても直ちに増援が配備される。',
    flavorQuote: '重厚なる鉄壁、崩れてなお補給を呼ぶ。',
    imageUrl: '/cards/I.jpg',
  },
  J: {
    letter: 'J',
    name: 'Joker',
    japaneseName: '死神',
    points: 6,
    category: 'demon',
    description: 'バトルに負けた場合、プレイヤーを1人選ぶ。そのプレイヤーの手札からランダムに1枚選び自分のポイントにする。',
    shortEffect: '敗北時：プレイヤーを1人選び手札からランダムに1枚奪って自分の得点に！',
    lore: '魂を狩り集める冷徹な死神。倒された時こそ、指名した者の命運を奪い去る。',
    flavorQuote: '負けたのではない、お前の魂を刈りに来たのだ。',
    imageUrl: '/cards/J.jpg',
  },
  K: {
    letter: 'K',
    name: 'Kirin',
    japaneseName: '麒麟',
    points: 6,
    category: 'myth',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '徳ある者のもとに舞い降りる幻獣。災厄に見舞われても天の恵みをもたらす。',
    flavorQuote: '天翔ける雷光が新たな運命を導く。',
    imageUrl: '/cards/K.jpg',
  },
  L: {
    letter: 'L',
    name: 'Leviathan',
    japaneseName: 'リヴァイアサン',
    points: 6,
    category: 'beast',
    description: 'バトルに負けた場合、全員の手札を回収して山札とともにシャッフルして同じ枚数配りなおす。',
    shortEffect: '敗北時：全員の手札と山札を合体リシャッフル！',
    lore: '深淵の海を統べる大怪獣。混沌の大渦を巻き起こし、盤面を白紙に戻す。',
    flavorQuote: '渦潮よ、すべてを混沌の深海へ巻き込め！',
    imageUrl: '/cards/L.jpg',
  },
  M: {
    letter: 'M',
    name: 'Minotaur',
    japaneseName: 'ミノタウロス',
    points: 5,
    category: 'beast',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '迷宮の奥底に潜む牛頭の狂戦士。退けられても迷宮から新たな獲物を掘り起こす。',
    flavorQuote: '迷いし者よ、我が斧の錆となれ。',
    imageUrl: '/cards/M.jpg',
  },
  N: {
    letter: 'N',
    name: 'Nymph',
    japaneseName: 'ニンフ',
    points: 5,
    category: 'spirit',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '清らかな泉や森に宿る妖精。ピンチの際に森の秘宝を手渡してくれる。',
    flavorQuote: '森のささやきが、新しい力を授けてくれるわ。',
    imageUrl: '/cards/N.jpg',
  },
  O: {
    letter: 'O',
    name: 'Ogre',
    japaneseName: 'オーガ',
    points: 5,
    category: 'beast',
    description: 'バトルに負けた場合、相手の手札を見る。',
    shortEffect: '敗北時：対戦相手の手札を覗き見る',
    lore: '狡猾な知恵を備えた怪力無双の鬼。敗北の痛みを耐え、相手の懐を暴き立てる。',
    flavorQuote: 'フン、お前の手のうちは丸見えだぞ！',
    imageUrl: '/cards/O.jpg',
  },
  P: {
    letter: 'P',
    name: 'Prince',
    japaneseName: '王子',
    points: 5,
    category: 'human',
    description: 'バトルに負けた場合、相手の手札を全員に公開させる。',
    shortEffect: '敗北時：対戦相手の手札を全員に白日の下に公開',
    lore: '王室の若き継承者。王家の告発力をもって相手の策謀を公衆の前に曝け出す。',
    flavorQuote: '不正を暴き、民衆の前に真実を明らかにしよう！',
    imageUrl: '/cards/P.jpg',
  },
  Q: {
    letter: 'Q',
    name: 'Queen',
    japaneseName: '女王',
    points: 4,
    category: 'human',
    description: 'バトルに負けた場合、プレイヤーを1人指名して手札を全員に公開させる。',
    shortEffect: '敗北時：任意の1人を指名して手札を全員公開させる',
    lore: '宮廷を牛耳る冷徹な王妃。敗北に動じることなく、標的の秘密を白日の下に晒す。',
    flavorQuote: '私の威光に隠し事は許されません。すべてを見せなさい。',
    imageUrl: '/cards/Q.jpg',
  },
  R: {
    letter: 'R',
    name: 'Revolutionary',
    japaneseName: '革命家',
    points: 4,
    category: 'human',
    description: 'バトルに勝った場合、全てのカードの強さが逆転する。',
    shortEffect: '勝利時：世界の序列が逆転！(Zが最強、Aが最弱へ)',
    lore: '旧体制の打倒を叫ぶ変革者。弱者が強者を討ち果たす新秩序を創り出す。',
    flavorQuote: '今日より弱者が支配者だ！ 革命の旗を掲げよ！',
    imageUrl: '/cards/R.jpg',
  },
  S: {
    letter: 'S',
    name: 'Soldier',
    japaneseName: '兵士',
    points: 4,
    category: 'human',
    description: 'バトルに負けた場合、1枚ドローする。',
    shortEffect: '敗北時：山札から1枚ドロー',
    lore: '前線を支える不屈の歩兵。倒れても後続の部隊が即座に戦線へ合流する。',
    flavorQuote: '倒れても仲間が続く。我が軍の行進は止まらない！',
    imageUrl: '/cards/S.jpg',
  },
  T: {
    letter: 'T',
    name: 'Troll',
    japaneseName: 'トロール',
    points: 3,
    category: 'beast',
    description: 'バトルに負けた場合、全員の手札を見る。',
    shortEffect: '敗北時：生存する全員の手札をすべて覗き見る',
    lore: '巨躯を誇る洞窟の主。殴り倒された怒りで周囲全員の手札を凝視する。',
    flavorQuote: 'オレを怒らせたな…全員の持ち物見せろ！',
    imageUrl: '/cards/T.jpg',
  },
  U: {
    letter: 'U',
    name: 'Unicorn',
    japaneseName: 'ユニコーン',
    points: 3,
    category: 'myth',
    description: 'バトルに勝った場合、このバトルでのカードの効果をすべて無効にする。',
    shortEffect: '勝利時：この戦闘に関わる全カード効果を完全無効化',
    lore: '角に浄化の奇跡を秘めた聖獣。勝利した瞬間、あらゆる魔術的効果を無に帰す。',
    flavorQuote: '清浄なる角よ、一切の邪なる呪法を祓え。',
    imageUrl: '/cards/U.jpg',
  },
  V: {
    letter: 'V',
    name: 'Vampire',
    japaneseName: '吸血鬼',
    points: 2,
    category: 'demon',
    description: 'バトルに負けた場合、相手の手札を見て好きなカードを手札に加える。',
    shortEffect: '敗北時：対戦相手の手札を見て1枚強奪して自分の手札へ！',
    lore: '夜を支配する吸血貴族。敗れた獲物の血肉と手札を啜り、我が物とする。',
    flavorQuote: 'その手札の力…我が身の糧として頂こう。',
    imageUrl: '/cards/V.jpg',
  },
  W: {
    letter: 'W',
    name: 'Werewolf',
    japaneseName: '狼男',
    points: 2,
    category: 'beast',
    description: 'バトルに負けた場合、山札のすべてのカードを見て好きなカードを1枚手札に加える。',
    shortEffect: '敗北時：山札を全確認して好きなカードを1枚サーチ！',
    lore: '月夜に狂気と野生を覚醒させる人狼。敗走の最中に群れの秘奥から最強の獲物を嗅ぎつける。',
    flavorQuote: 'ウォォォン！ 山札の奥底から獲物を引きずり出してやる！',
    imageUrl: '/cards/W.jpg',
  },
  X: {
    letter: 'X',
    name: 'Xenos',
    japaneseName: '異世界人',
    points: 1,
    category: 'human',
    description: 'バトルに負けた場合、全員の手札を見て好きなカードを1枚手札に加える。',
    shortEffect: '敗北時：他全員の手札を見て好きなカードを1枚強奪！',
    lore: '時空を超えて迷い込んだ異世界からの転生者。この世の掟を無視して他者の秘奥を掠め取る。',
    flavorQuote: 'この世界のルール、僕のチート能力で書き換えるよ。',
    imageUrl: '/cards/X.jpg',
  },
  Y: {
    letter: 'Y',
    name: 'Youth',
    japaneseName: '青年',
    points: 1,
    category: 'human',
    description: 'Zero～ゼロ～に勝った場合、ゲームを終了しポイントに関係なく勝利する。',
    shortEffect: 'Zero(Z)に勝利すると即座にゲーム完全勝利！',
    lore: '名もなき未熟な青年。何者でもないゼロの虚無に打ち勝つ時、奇跡の戴冠を果たす。',
    flavorQuote: '何もないゼロになんて、絶対に負けない！',
    imageUrl: '/cards/Y.jpg',
  },
  Z: {
    letter: 'Z',
    name: 'Zero',
    japaneseName: 'ゼロ',
    points: 0,
    category: 'spirit',
    description: '効果なし。',
    shortEffect: '効果なし (革命時は最強カードに！)',
    lore: '始まりにして終わり、虚無の象徴。通常は最弱だが、革命の嵐が吹き荒れる時、頂点に君臨する。',
    flavorQuote: '無から生まれ、無へと還る。',
    imageUrl: '/cards/Z.jpg',
  },
};

export const ALL_LETTERS: Letter[] = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'W', 'X', 'Y', 'Z'
];

export const getDeckList = (): CardData[] => {
  return ALL_LETTERS.map((letter) => CARD_DATABASE[letter]);
};

/**
 * Compare two cards:
 * Returns > 0 if cardA beats cardB
 * Returns < 0 if cardB beats cardA
 * Returns 0 if equal
 *
 * Normal: A (index 0) is strongest, Z (index 25) is weakest.
 * Revolution: Z is strongest, A is weakest.
 */
export const compareCards = (cardA: CardData, cardB: CardData, isRevolution: boolean): number => {
  const indexA = ALL_LETTERS.indexOf(cardA.letter);
  const indexB = ALL_LETTERS.indexOf(cardB.letter);

  if (indexA === indexB) return 0;

  if (isRevolution) {
    // Higher index in ALL_LETTERS is stronger (Z > A)
    return indexA > indexB ? 1 : -1;
  } else {
    // Lower index in ALL_LETTERS is stronger (A > Z)
    return indexA < indexB ? 1 : -1;
  }
};
